# ServerProperties
server:
  port: 8080
  servlet:
    context-path: /community

# ThymeleafProperties
spring:
  thymeleaf:
    cache: false
  # DataSourceProperties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: '040118'
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 30000
# MailProperties
  mail:
    host: smtp.163.com
    port: 465
    username: foeshm@163.com
    password: XCcuEREt3ZSFL5pX
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

# MybatisProperties
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nowcoder.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
#Logger
logging:
  level:
    com.nowcoder.community: debug

#Community
community:
  path:
    domain: http//:localhost:8080